initial multi-arch implementation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,13 +25,16 @@ jobs:
       - name: Log in to GHCR
         run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
 
-      - name: Build Docker image
+      - name: Build Multi-Arch Docker Image
         run: |
-          docker build --no-cache -t $IMAGE_NAME:$UNIQUE_TAG --build-arg API_PORT=${{ env.API_PORT }} .
+          docker buildx create --use
+          docker buildx build --platform linux/amd64,linux/arm64 \
+            --no-cache -t $IMAGE_NAME:$UNIQUE_TAG --build-arg API_PORT=${{ env.API_PORT }} .
 
       - name: Push Docker image with unique tag to GHCR
         run: |
-          docker push $IMAGE_NAME:$UNIQUE_TAG
+          docker buildx create --use
+          docker buildx push $IMAGE_NAME:$UNIQUE_TAG
 
       - name: Upload code artifact
         uses: actions/upload-artifact@v4
@@ -154,22 +157,27 @@ jobs:
 
       - name: Pull the Docker image
         run: |
-          docker pull $IMAGE_NAME:$UNIQUE_TAG || echo "Image not found, might not have been built yet."
+          docker buildx create --use
+          docker buildx pull --platform linux/arm64 $IMAGE_NAME:$UNIQUE_TAG || echo "Image not found for ARM64."
 
-      - name: Tag Docker image with commit SHA and latest
+      - name: Tag Multi-Arch Docker image with commit SHA and latest
         run: |
+          docker buildx create --use
           IMAGE_SHA_TAG=$IMAGE_NAME:${{ github.sha }}
           IMAGE_LATEST_TAG=$IMAGE_NAME:latest
-          docker tag $IMAGE_NAME:$UNIQUE_TAG $IMAGE_SHA_TAG
-          docker tag $IMAGE_NAME:$UNIQUE_TAG $IMAGE_LATEST_TAG
+          docker buildx imagetools create --tag $IMAGE_SHA_TAG $IMAGE_NAME:$UNIQUE_TAG
+          docker buildx imagetools create --tag $IMAGE_LATEST_TAG $IMAGE_NAME:$UNIQUE_TAG
           echo "IMAGE_SHA_TAG=$IMAGE_SHA_TAG" >> $GITHUB_ENV
           echo "IMAGE_LATEST_TAG=$IMAGE_LATEST_TAG" >> $GITHUB_ENV
 
-      - name: Push Docker image with SHA and latest tags
+      - name: Push Multi-Arch Docker image with SHA and latest tags
         run: |
-          docker push $IMAGE_NAME:$UNIQUE_TAG
-          docker push $IMAGE_SHA_TAG
-          docker push $IMAGE_LATEST_TAG
+          docker buildx create --use
+          docker buildx build --platform linux/amd64,linux/arm64 \
+            -t $IMAGE_NAME:$UNIQUE_TAG \
+            -t $IMAGE_NAME:$IMAGE_SHA_TAG \
+            -t $IMAGE_NAME:$IMAGE_LATEST_TAG \
+            --push .
 
       - name: Notify Developer
         if: success()
